### ISSUE TITLE
[BUG]: Since the 1.67.0 update, bananas and coconuts in trees spawning around 3/4ths less fruit (when spawning fruit)

### ISSUE THREAD

**Issue by MadHareGraphics** [typical-developers/oaklands-feedback#1006]
### Roblox Username

White_Rabbit143

### What version did this issue occur in?

1.67.0

### Describe the issue in detail.

Since the 1.67.0 update, bananas and coconuts in trees spawning around 3/4ths less fruit (when spawning fruit).
When one of the palm trees (regular palm and king, haven't checked the queen palm yet) are spawned with fruit in them, it is in the area of about 75% of its spawn points in the tree don't occur, regular palm only spawn one, rarely 2 coconuts, and Banana trees only spawn up to 4 or 5 at most. ground coconuts seem fine, and most other trees are alright (except apple but that's a different issue) just the coconut bearing palms and king palms.

### Provide some images / videos of the issue in action.

![Screenshot 2024-09-26 200958](https://github.com/user-attachments/assets/d18b27cf-1824-4927-8f98-63b75d32377f)
![Screenshot 2024-09-26 201258](https://github.com/user-attachments/assets/54c72951-ef1b-4490-89e8-7cdbaa34b750)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
I have been going insane wondering if there was a memory leak with fruits, and you my friend, just found it! Thanks a lot. The issue was that only one leaf was being considered for generation (sort of, in simple terms at least). This resulted in all the other fruit spawns never appearing in the world, hence never being cleaned up, creating a small memory leak.

Thanks!
