### ISSUE TITLE
[BUG]: Schematics and plot sign lingering AFTER leaving 

### ISSUE THREAD

**Issue by Fireparakeet** [typical-developers/oaklands-feedback#1042]
### Roblox Username

Fireparakeet

### What version did this issue occur in?

1.68.0

### Describe the issue in detail.

Even after leaving, some of my base's schematics stay occupied on the same plot with collision and all. When this happens, I cannot reload into the same server as all of my saves stay indefinitely loading in the menu.

This has happened twice in the span of an hr in private servers, it might've happened in publics as well, but I did not have confirmation from other people at the time. The f9 logs do not have any unusual errors from both the people in the server and me, the plot owner.

### Provide some images / videos of the issue in action.

![oaklandsb1](https://github.com/user-attachments/assets/9f71a17c-fa77-475d-aa1d-bf44e9b599d2)
![image](https://github.com/user-attachments/assets/6a4b5d86-89ea-42ee-bc39-4ed827e515b0)
![image](https://github.com/user-attachments/assets/2e6b6860-56c4-4f81-9268-51f3f029fd2b)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by Fireparakeet** [comment]
Update on this, when someone else loads into the same plot they can interact with structures like doors and drawers NOTHING comes out of the drawers though even if they contain items. The only thing that can be taken from this "ghost plot" are schematics in which the person loaded in can replicate the designs that linger.
![image](https://github.com/user-attachments/assets/681cfc34-b964-4079-8489-60f81215800e)
![image](https://github.com/user-attachments/assets/2c91060f-6da2-484e-9f20-3ee3e3bf570d)
![image](https://github.com/user-attachments/assets/eaf1bf06-8211-41f3-ab3c-a7855740c886)

**Comment by AkkozaDevelops** [comment]
@HooferDevelops this could be due to the data size of the property (106.12umb) which is roughly 30ish datastores worth of data; so it could be due to the datastores throttling?

Not entirely sure what could be the issue but I could not replicate it in a private server of my own.

Upon checking in the server with the broken property, it seems that the Data module never released Para's Id from the ActivePlayers table (so they couldn't load again), but ProfileService released their data, and their data saved perfectly fine.

When I manually cleared the ActivePlayers table for their Id, they loaded their property in a different spot and it cleared the old "ghost" schematics, showing they still had their UUIDs (so possibly behaviors not unloading, or the Player module getting timed out while trying to destroy them all?)

**Only Schematics, not items**

These are just notes to help you figure out the possible issue, as I myself have no clue.

**Comment by HooferDevelops** [comment]
No, it wouldn't be. I'm looking into it right now and will likely need to join them when it happens.
