### ISSUE TITLE
[BUG]: Servers have high ping

### ISSUE THREAD

**Issue by Darth1116** [typical-developers/oaklands-feedback#206]
### Roblox Username

ganeshap4052

### What version did this issue occur in?

the newest verison idk the niumbers

### Describe the issue in detail.

ok so ifk why but when i go in a public server my ping it like 400ms -700ms or something around 400ms but when i go in a solo session or a privite by my self i get 77ms aroung there could be on my end but idk 

### Provide some images / videos of the issue in action.

![IMG_6436](https://github.com/typical-developers/oaklands-feedback/assets/158644238/49c3e027-ebf1-46c6-a0cb-4bed8dda1031)
![IMG_6437](https://github.com/typical-developers/oaklands-feedback/assets/158644238/d8408576-7092-4ca3-9d13-6a70dc859731)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Darth1116** [comment]
sorry for miss typing i have bad type i miss spell words

**Comment by Darth1116** [comment]
also dm on discord if this gett resolved or just say bug fixs in the oak lands news  section of the server my  discord user is my user for this btw if u care

**Comment by LuckFire** [comment]
This isn't something we can necessarily "fix". There's two things that can cause high ping:
- The Roblox servers themselves (usually because of region)
- Large bases being loaded
- Your own internet connection
- Everything combined

We can only do so much to optimize the game, after a while it's just not our fault and we're nearing that point. If people have really large bases and load them in public servers, it's obviously going to create issues for that server. There's nothing we can do about it.

**Comment by Darth1116** [comment]
i think its a me iusse cuz now i can peacfully play with no high pung so i think it my end or roblox

**Comment by Darth1116** [comment]
sorry for bad typing

**Comment by LuckFire** [comment]
No worries 👍🏼
