### ISSUE TITLE
[BUG]: The unit grid on schematics are not correct and the arrows go backwards

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#35]
### Roblox Username

BrenoGamerBr205

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

The texture of the unit grid is not correct in some schematics (image) and the arrow goes backwards, it's confusing.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/143729780/213c5443-183a-479d-9ece-237dabfd9920)

https://github.com/typical-developers/oaklands-feedback/assets/143729780/38fb8d0a-d6a1-41ec-8948-afcde5b6b9bf

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Grid on Schematics): With the way Roblox works there's no simple solution to this, and it'd require a lot of calculated offsetting and it flat out wouldn't work for stuff like spheres or doors.

It's meant to be a bit of a guide, but more-of just a texture. Though it does work decently well with more square objects.

Directional Arrows): While I might make it so that the directional arrows by default aren't moving, there's no true way to make it synced to the direction of the original selection.

The way that we handle placements prevents us from actually receiving the data as to what the object was originally, you're not actually moving the model seen on your base you're instead moving around a hologram.

**Comment by ManancialGD** [comment]
> Grid on Schematics): With the way Roblox works there's no simple solution to this, and it'd require a lot of calculated offsetting and it flat out wouldn't work for stuff like spheres or doors.
> 
> It's meant to be a bit of a guide, but more-of just a texture. Though it does work decently well with more square objects.
> 
> Directional Arrows): While I might make it so that the directional arrows by default aren't moving, there's no true way to make it synced to the direction of the original selection.
> 
> The way that we handle placements prevents us from actually receiving the data as to what the object was originally, you're not actually moving the model seen on your base you're instead moving around a hologram.

I have some knoledge in Blender, I don't know how to program, but I am a 3D artist. Do you think I can help in anyway with the grid thing? For free. I really want it to work right, I am enjoying the game very much and it would be useful.
