### ISSUE TITLE
[BUG]: door schematics cannot be replicated

### ISSUE THREAD

**Issue by JackOfCool** [typical-developers/oaklands-feedback#42]
### Roblox Username

JackThePC_Overlord

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

You can't replicate door schematics 

### Provide some images / videos of the issue in action.

n/a

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by manncomelonondiscord** [comment]
https://github.com/typical-developers/oaklands-feedback/assets/154050833/dfdd5380-1171-4f53-8fef-cfff3a61486b

footage of the no door replicating bug in action, look at the left side of the screen and you can see i'm pressing R and its not replicating

**Comment by LuckFire** [comment]
Looking into this more, this is likely due to the fact you have to *separately* purchase door schematics, as they are not reusable when you purchase them once (they are also considered "structures"). However, a notice that the structure cannot be replicated would be nice, though, that change will have to wait until the build mode rewrite.

**Comment by HooferDevelops** [comment]
> Looking into this more, this is likely due to the fact you have to _separately_ purchase door schematics, as they are not reusable when you purchase them once (they are also considered "structures"). However, a notice that the structure cannot be replicated would be nice, though, that change will have to wait until the build mode rewrite.

All doors are schematics except for the glass door.
