### ISSUE TITLE
[BUG]: Trailer Teleportation

### ISSUE THREAD

**Issue by chi-kiz** [typical-developers/oaklands-feedback#44]
### Roblox Username

BUG_JUICER

### What version did this issue occur in?

1.39.5 Onward

### Describe the issue in detail.

In short, trailers teleport for some reason when connected together without a car leading them, I believe. It's inconvenient and doesn't bring the items with them. I do not have the media but thank you for the Roblox user 'timmy9834' for providing.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/104881769/053b701d-db59-4188-acfb-6332414c8ff3)

https://github.com/typical-developers/oaklands-feedback/assets/104881769/15b629b1-76f1-49a4-9c75-1cc07e859333

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Pretty sure this occurs due to our blocking system, as you can see the trailers move just enough out of the plot to be outside of the client sided barrier right as the player in the truck on the left drives by.

Do you know for a fact that the player on the left was blocked? I don't entirely understand the issue for myself, but we've seen this in many other cases such as Crates flinging out of the world due to this.

I'm sure @HooferDevelops knows the solution to this though

**Comment by chi-kiz** [comment]
Oh definitely, they move out of blocking range but this player reports it even happening without any players near, just when the trailers manage to be out of sight for them. It's less of other players being near and I believe it being a spontaneous issue, of which I wouldn't know why. Thanks for the response however! Github's fun to use.

**Comment by HooferDevelops** [comment]
This is definitely a network ownership bug. I will look into the issue when I have more time. Are these trailers freshly spawned in? Have they been disconnected from the vehicle prior? Are they from when you rejoined the game? Just need some more information for easier reproduction.

**Comment by HooferDevelops** [comment]
I believe I have figured out the root cause of this, I think it is in relation to the trailer being unhitched, allowing the trailers to retain network ownership. We will have to find out in v1.43.0 though.
