### ISSUE TITLE
[Exploit]: anticheat permanently ban

### ISSUE THREAD

**Issue by Flayzik** [typical-developers/oaklands-feedback#506]
### Roblox Username

SHE_DELOR

### What version did this issue occur in?

1.55.0

### Describe the issue in detail.

I just used fps unlocker for the best exp, and at one point I got banned.

### Provide some images / videos of the issue in action.

Don't have

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by 1Peekaboo1** [comment]
you are a shameless liar and won't be unbanned. Farewell.

**Comment by Flayzik** [comment]
If you don't want to, don't believe it, but I'm telling the truth.

**Comment by 1Peekaboo1** [comment]
tElLiNg ThE tRuTh!

yeah, how many of you "truth tellers" were caught blatantly lying when Hoofer pulled up the logs of what you tried to execute. You geneuienly think that our anti-cheat just bans on a whim just because it felt like it? And brother, this excuse of "My fps unlocker banned me!!" is as old as roblox itself. FPS Unlocker CANNOT get you banned. It merely sets a single flag in the client to off. Get lost, we don't appreciate liars here.

**Comment by Flayzik** [comment]
Ok-_-

**Comment by LuckFire** [comment]
You come onto our GitHub to report an "issue" with our anti-cheat, however, provide no valid proof that you were able to reproduce that it was an FPS unlocker that caused your ban? Not only do you do that, you don't provide a proper Roblox username, seeing how I cannot find you on the search.

We can see the *exact* reason why you were banned and what you did. We do not ban for FPS unlockers. Please don't come onto our GitHub for **reporting genuine issues** just to complain about your own poor decision making.
