### ISSUE TITLE
[BUG]: Fps drops to 15 , sometimes the picture freezes,

### ISSUE THREAD

**Issue by helloinchik7777** [typical-developers/oaklands-feedback#518]
### Roblox Username

helloinchik7777

### What version did this issue occur in?

1.55.0

### Describe the issue in detail.

I have a powerful pc but game suspends, sometimes VERY strong that the picture freezes, in other plays all normal, when I played before the update to all was good and now no.(I know that there is already a version 1.55.3, but there is still the same game lags.)
I had to reduce the quality of the video because it weighed over 10 mb.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/169542281/58fddb18-7460-4620-9a16-2767ad9c5cf5

### Before Submitting

- [x] I have confirmed that nobody else reported this issue.
- [x] The details of this report are legitimate.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
I think the issue is related to Clientside physics calculation, where they decided to reduce lag to servers, but they gave more strain to clients, and potentially security risk (exploiters can teleport parts to anywhere within network ownership). My recommend fix is do clientside physics calculation on close proximity (~40 studs), and anchor if they detect this object is "sleeping" (velocity's magnitude is 0).

**Comment by tomsterBG** [comment]
Just joined a public server and drove away from my base. Worst mistake. Game froze for 2-3 minutes and I think it unloaded my base because the people with money in the server (aka big bases) didn't leave or join so it's probably not that.
Here's some dev console stuff if it matters:
![image](https://github.com/typical-developers/oaklands-feedback/assets/117642342/52be4b50-ebbc-4426-9302-f5d295b29692)

**Comment by helloinchik7777** [comment]
So it's not the game that's the problem? Or what?

**Comment by 1Nugget2Poulet** [comment]
I had the same problem, i was going from 120 fps to 20-10 fps bcs i had loads of cheese and magma trees stocked up in big storage wich probably caused too much collision, the only way i fixed it was by putting every things in the new storage system.

**Comment by helloinchik7777** [comment]
Okay, thanks a lot, I'll close this thread when I get home.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
> I think the issue is related to Clientside physics calculation, where they decided to reduce lag to servers, but they gave more strain to clients, and potentially security risk (exploiters can teleport parts to anywhere within network ownership). My recommend fix is do clientside physics calculation on close proximity (~40 studs), and anchor if they detect this object is "sleeping" (velocity's magnitude is 0).

they reverted in 1.55.4 as stated above, they need to find a solution to that
