### ISSUE TITLE
[BUG]: Property signs not showing the right property number

### ISSUE THREAD

**Issue by Alex-Purschwitz** [typical-developers/oaklands-feedback#635]
### Roblox Username

Buddermcman

### What version did this issue occur in?

1.58.4

### Describe the issue in detail.

The property signs show the wrong property number. The one i'm at is #4 and it shows #2

### Provide some images / videos of the issue in action.

![image_2024-06-17_211353873](https://github.com/typical-developers/oaklands-feedback/assets/162781117/fee1618a-d8f0-431c-8a11-427a81bf3b3a)
![image_2024-06-17_211419500](https://github.com/typical-developers/oaklands-feedback/assets/162781117/df24d177-2679-4fcd-91c9-35291d9ac4bd)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HDMICIDE** [comment]
if the one by the mines says 4 then that's because they based them off of the property numbers after shuffling, basically the numbers we have now are the same as like December, but for a solid 4ish months we had different plot numbers and all of them got shuffled but 1 and 5. if it doesn't say 4 then my reasoning is just wrong
