### ISSUE TITLE
[BUG]: When joining a server, around 50% of the time you will get stuck on the "Initializing Save Slots" screen

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#90]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.41.1

### Describe the issue in detail.

Title explained it pretty well, I've asked others if they have experienced this too and two others confirmed it (Invertedreality, Vanderfini). Only started happening after the halloween update.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/39076891/74bc1404-5f40-46f6-a084-77f38b465c51)
![image](https://github.com/typical-developers/oaklands-feedback/assets/39076891/c0b5231e-2017-4de1-8097-28fc0611d558)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by ZenizuDev** [comment]
I reported this in the chat before, happened sometime last week, around tuesday maybe, its not exclusive to the haloween update but the update may have caused more issues

**Comment by LuckFire** [comment]
In relation to what ZenizuDev said, this was something that has existed for a while but it seems to be occurring more -- my assumption is that there was some sort of internal change that's causing this to happen more but I'm not entirely sure so take that with a grain of salt (since I'm not sure what factors would impact datastore loading).

@HooferDevelops it'd be appreciated if there were some elaboration on this 🙏🏼
